import type { DecodedReplayPayload, ReplaySession } from "@open-session/sdk";

const baseTimestamp = new Date("2026-05-01T09:24:18.120Z").getTime();
const pageUrl = "https://checkout.open.example/checkout?token=%5Bredacted%5D&email=%5Bredacted%5D&safe=visible";
const cartUrl = "https://checkout.open.example/cart?token=%5Bredacted%5D&email=%5Bredacted%5D&safe=visible";

const sampleSession: ReplaySession = {
  metadata: {
    appId: "sample-checkout",
    sessionId: "sample-checkout-failure",
    sdkVersion: "0.1.0",
    url: pageUrl,
    userAgent: "Mozilla/5.0 Open Sample Viewer",
    viewport: { width: 1440, height: 960 },
    createdAt: new Date(baseTimestamp).toISOString(),
  },
  events: [
    {
      id: "sample-lifecycle-init",
      kind: "lifecycle",
      name: "init",
      detail: "Checkout replay SDK initialized",
      timestamp: baseTimestamp,
      pageUrl,
    },
    {
      id: "sample-console-init",
      kind: "console",
      level: "info",
      args: ["결제 리플레이 SDK가 초기화되었습니다", { surface: "sample-checkout" }],
      redactions: [],
      timestamp: baseTimestamp + 42,
      pageUrl,
    },
    {
      id: "sample-navigation-checkout",
      kind: "navigation",
      navigationType: "pushState",
      fromUrl: cartUrl,
      toUrl: pageUrl,
      timestamp: baseTimestamp + 68,
      pageUrl,
    },
    {
      id: "sample-keydown-name",
      kind: "keydown",
      target: { strategy: "id", selector: "#recipient-name", tagName: "input" },
      key: "A",
      code: "KeyA",
      privacy: "safe",
      count: 4,
      lastTimestamp: baseTimestamp + 118,
      timestamp: baseTimestamp + 92,
      pageUrl,
    },
    {
      id: "sample-keydown-card",
      kind: "keydown",
      target: { strategy: "attribute", selector: "input[data-redacted]", tagName: "input", redacted: true },
      privacy: "masked",
      count: 12,
      lastTimestamp: baseTimestamp + 260,
      timestamp: baseTimestamp + 136,
      pageUrl,
    },
    {
      id: "sample-click-coupon",
      kind: "click",
      target: { strategy: "attribute", selector: 'button[data-testid="apply-coupon"]', tagName: "button" },
      button: 0,
      timestamp: baseTimestamp + 301,
      pageUrl,
    },
    {
      id: "sample-console-coupon",
      kind: "console",
      level: "log",
      args: ["고객이 결제 쿠폰을 적용했습니다", { discount: 3000, safe: true }],
      redactions: [],
      timestamp: baseTimestamp + 330,
      pageUrl,
    },
    {
      id: "sample-click-pay",
      kind: "click",
      target: { strategy: "attribute", selector: 'button[data-testid="submit-payment"]', tagName: "button" },
      button: 0,
      timestamp: baseTimestamp + 412,
      pageUrl,
    },
    {
      id: "sample-console-warn",
      kind: "console",
      level: "warn",
      args: ["결제 사전 승인 API 호출: 민감한 쿼리는 리플레이에서 마스킹되어야 합니다"],
      redactions: [],
      timestamp: baseTimestamp + 436,
      pageUrl,
    },
    {
      id: "sample-network-preauth",
      kind: "network",
      method: "POST",
      url: "https://api.open.example/payments/preauth?token=%5Bredacted%5D&email=%5Bredacted%5D",
      status: 200,
      durationMs: 128,
      ok: true,
      redactions: ["query:token", "query:email", "headers:default", "body:default"],
      timestamp: baseTimestamp + 590,
      pageUrl,
    },
    {
      id: "sample-network-approve",
      kind: "network",
      method: "POST",
      url: "https://api.open.example/payments/approve?session=%5Bredacted%5D",
      status: 502,
      durationMs: 642,
      count: 3,
      lastTimestamp: baseTimestamp + 1410,
      minDurationMs: 522,
      maxDurationMs: 642,
      ok: false,
      error: "Bad Gateway",
      redactions: ["query:session", "headers:default", "body:default"],
      timestamp: baseTimestamp + 1210,
      pageUrl,
    },
    {
      id: "sample-console-error",
      kind: "console",
      level: "error",
      args: ["결제 승인 응답 처리 실패", { code: "PG_BAD_GATEWAY", orderId: "ord_sample_1024" }],
      redactions: [],
      timestamp: baseTimestamp + 1242,
      pageUrl,
    },
    {
      id: "sample-error",
      kind: "error",
      name: "PaymentApprovalError",
      message: "결제 진행중 오류발생",
      componentStack: "at PaymentSubmitButton (CheckoutPayment.tsx:42:11)\nat CheckoutSummary (CheckoutSummary.tsx:88:5)",
      timestamp: baseTimestamp + 1306,
      pageUrl,
    },
  ],
  errors: [
    {
      id: "sample-error",
      kind: "error",
      name: "PaymentApprovalError",
      message: "결제 진행중 오류발생",
      componentStack: "at PaymentSubmitButton (CheckoutPayment.tsx:42:11)\nat CheckoutSummary (CheckoutSummary.tsx:88:5)",
      timestamp: baseTimestamp + 1306,
      pageUrl,
    },
  ],
  stats: {
    eventCount: 13,
    droppedEvents: 0,
    truncatedEvents: 0,
    redactionCount: 7,
  },
  privacy: {
    defaultRedactions: ["password-no-key-values", "sensitive-selector-redaction", "network-body-header-redaction", "sensitive-query-redaction"],
    notes: ["Password-like inputs are captured as masked keydown events only.", "Network headers and bodies are excluded by default."],
  },
};

export const sampleDecodedReplay: DecodedReplayPayload = {
  session: sampleSession,
  envelope: {
    version: 1,
    createdAt: new Date(baseTimestamp + 1500).toISOString(),
    sdk: { name: "@open-session/sdk", version: sampleSession.metadata.sdkVersion },
    app: { id: sampleSession.metadata.appId, url: sampleSession.metadata.url },
    session: { id: sampleSession.metadata.sessionId },
    crypto: {
      algorithm: "AES-GCM",
      kdf: "PBKDF2",
      salt: "sample-salt",
      iv: "sample-iv",
      iterations: 120000,
      keyLength: 256,
    },
    compression: {
      algorithm: "brotli",
      originalBytes: 6840,
      compressedBytes: 2140,
      level: 6,
    },
    stats: sampleSession.stats,
    payloadFormat: "compact-session-v1",
    payload: "sample-viewer-payload",
  },
};
